//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isban.Maps.Bussiness.MYAService {

    public class respuesta
    {
        public string CodRet { get; set; }
        public string ClienteEstado { get; set; }
        public System.Collections.Generic.List<Destino> Destinos { get; set; }
    }

    public class Destino {
        public string DestinoTipo { get; set; }
        public string DestinoSecuencia { get; set; }
        public string DestinoDescripcion { get; set; }
        public string DestinoEmpresaCel { get; set; }
        public string DestinoEstado { get; set; }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.mya.ar.bsch", ConfigurationName="MYAService.Services")]
    public interface Services {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="getEstadoCliente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getEstadoClienteReturn")]
        Isban.Maps.Bussiness.MYAService.getEstadoClienteResponse getEstadoCliente(Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getEstadoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getEstadoClienteResponse> getEstadoClienteAsync(Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="updateMensaje", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateMensajeReturn")]
        Isban.Maps.Bussiness.MYAService.updateMensajeResponse updateMensaje(Isban.Maps.Bussiness.MYAService.updateMensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateMensaje", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateMensajeResponse> updateMensajeAsync(Isban.Maps.Bussiness.MYAService.updateMensajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="updateMensajeRecarga", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateMensajeRecargaReturn")]
        Isban.Maps.Bussiness.MYAService.updateMensajeRecargaResponse updateMensajeRecarga(Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateMensajeRecarga", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateMensajeRecargaResponse> updateMensajeRecargaAsync(Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="updateDestinos", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateDestinosReturn")]
        Isban.Maps.Bussiness.MYAService.updateDestinosResponse updateDestinos(Isban.Maps.Bussiness.MYAService.updateDestinosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateDestinos", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateDestinosResponse> updateDestinosAsync(Isban.Maps.Bussiness.MYAService.updateDestinosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="registrarConDestino", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="registrarConDestinoReturn")]
        Isban.Maps.Bussiness.MYAService.registrarConDestinoResponse registrarConDestino(Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="registrarConDestino", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.registrarConDestinoResponse> registrarConDestinoAsync(Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="getParametros", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getParametrosReturn")]
        Isban.Maps.Bussiness.MYAService.getParametrosResponse getParametros(Isban.Maps.Bussiness.MYAService.getParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getParametros", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getParametrosResponse> getParametrosAsync(Isban.Maps.Bussiness.MYAService.getParametrosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="registrar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="registrarReturn")]
        Isban.Maps.Bussiness.MYAService.registrarResponse registrar(Isban.Maps.Bussiness.MYAService.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.registrarResponse> registrarAsync(Isban.Maps.Bussiness.MYAService.registrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="updateEstadoCliente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateEstadoClienteReturn")]
        Isban.Maps.Bussiness.MYAService.updateEstadoClienteResponse updateEstadoCliente(Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateEstadoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateEstadoClienteResponse> updateEstadoClienteAsync(Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.mya.ar.bsch).
        [System.ServiceModel.OperationContractAttribute(Action="getSuscripciones", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSuscripcionesReturn")]
        Isban.Maps.Bussiness.MYAService.getSuscripcionesResponse getSuscripciones(Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSuscripciones", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getSuscripcionesResponse> getSuscripcionesAsync(Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstadoCliente", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getEstadoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getEstadoClienteRequest() {
        }
        
        public getEstadoClienteRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstadoClienteResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getEstadoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getEstadoClienteReturn;
        
        public getEstadoClienteResponse() {
        }
        
        public getEstadoClienteResponse(string getEstadoClienteReturn) {
            this.getEstadoClienteReturn = getEstadoClienteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensaje", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateMensajeRequest() {
        }
        
        public updateMensajeRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensajeResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateMensajeReturn;
        
        public updateMensajeResponse() {
        }
        
        public updateMensajeResponse(string updateMensajeReturn) {
            this.updateMensajeReturn = updateMensajeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensajeRecarga", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeRecargaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateMensajeRecargaRequest() {
        }
        
        public updateMensajeRecargaRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensajeRecargaResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeRecargaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateMensajeRecargaReturn;
        
        public updateMensajeRecargaResponse() {
        }
        
        public updateMensajeRecargaResponse(string updateMensajeRecargaReturn) {
            this.updateMensajeRecargaReturn = updateMensajeRecargaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDestinos", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateDestinosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateDestinosRequest() {
        }
        
        public updateDestinosRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDestinosResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateDestinosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateDestinosReturn;
        
        public updateDestinosResponse() {
        }
        
        public updateDestinosResponse(string updateDestinosReturn) {
            this.updateDestinosReturn = updateDestinosReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarConDestino", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarConDestinoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public registrarConDestinoRequest() {
        }
        
        public registrarConDestinoRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarConDestinoResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarConDestinoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string registrarConDestinoReturn;
        
        public registrarConDestinoResponse() {
        }
        
        public registrarConDestinoResponse(string registrarConDestinoReturn) {
            this.registrarConDestinoReturn = registrarConDestinoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParametros", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getParametrosRequest() {
        }
        
        public getParametrosRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParametrosResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getParametrosReturn;
        
        public getParametrosResponse() {
        }
        
        public getParametrosResponse(string getParametrosReturn) {
            this.getParametrosReturn = getParametrosReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrar", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public registrarRequest() {
        }
        
        public registrarRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string registrarReturn;
        
        public registrarResponse() {
        }
        
        public registrarResponse(string registrarReturn) {
            this.registrarReturn = registrarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEstadoCliente", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateEstadoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateEstadoClienteRequest() {
        }
        
        public updateEstadoClienteRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEstadoClienteResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateEstadoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateEstadoClienteReturn;
        
        public updateEstadoClienteResponse() {
        }
        
        public updateEstadoClienteResponse(string updateEstadoClienteReturn) {
            this.updateEstadoClienteReturn = updateEstadoClienteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSuscripciones", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getSuscripcionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getSuscripcionesRequest() {
        }
        
        public getSuscripcionesRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSuscripcionesResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getSuscripcionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getSuscripcionesReturn;
        
        public getSuscripcionesResponse() {
        }
        
        public getSuscripcionesResponse(string getSuscripcionesReturn) {
            this.getSuscripcionesReturn = getSuscripcionesReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesChannel : Isban.Maps.Bussiness.MYAService.Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<Isban.Maps.Bussiness.MYAService.Services>, Isban.Maps.Bussiness.MYAService.Services {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.getEstadoClienteResponse Isban.Maps.Bussiness.MYAService.Services.getEstadoCliente(Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest request) {
            return base.Channel.getEstadoCliente(request);
        }
        
        public string getEstadoCliente(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest inValue = new Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.getEstadoClienteResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).getEstadoCliente(inValue);
            return retVal.getEstadoClienteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getEstadoClienteResponse> Isban.Maps.Bussiness.MYAService.Services.getEstadoClienteAsync(Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest request) {
            return base.Channel.getEstadoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getEstadoClienteResponse> getEstadoClienteAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest inValue = new Isban.Maps.Bussiness.MYAService.getEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).getEstadoClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.updateMensajeResponse Isban.Maps.Bussiness.MYAService.Services.updateMensaje(Isban.Maps.Bussiness.MYAService.updateMensajeRequest request) {
            return base.Channel.updateMensaje(request);
        }
        
        public string updateMensaje(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateMensajeRequest inValue = new Isban.Maps.Bussiness.MYAService.updateMensajeRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.updateMensajeResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateMensaje(inValue);
            return retVal.updateMensajeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateMensajeResponse> Isban.Maps.Bussiness.MYAService.Services.updateMensajeAsync(Isban.Maps.Bussiness.MYAService.updateMensajeRequest request) {
            return base.Channel.updateMensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateMensajeResponse> updateMensajeAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateMensajeRequest inValue = new Isban.Maps.Bussiness.MYAService.updateMensajeRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateMensajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.updateMensajeRecargaResponse Isban.Maps.Bussiness.MYAService.Services.updateMensajeRecarga(Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest request) {
            return base.Channel.updateMensajeRecarga(request);
        }
        
        public string updateMensajeRecarga(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest inValue = new Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.updateMensajeRecargaResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateMensajeRecarga(inValue);
            return retVal.updateMensajeRecargaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateMensajeRecargaResponse> Isban.Maps.Bussiness.MYAService.Services.updateMensajeRecargaAsync(Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest request) {
            return base.Channel.updateMensajeRecargaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateMensajeRecargaResponse> updateMensajeRecargaAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest inValue = new Isban.Maps.Bussiness.MYAService.updateMensajeRecargaRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateMensajeRecargaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.updateDestinosResponse Isban.Maps.Bussiness.MYAService.Services.updateDestinos(Isban.Maps.Bussiness.MYAService.updateDestinosRequest request) {
            return base.Channel.updateDestinos(request);
        }
        
        public string updateDestinos(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateDestinosRequest inValue = new Isban.Maps.Bussiness.MYAService.updateDestinosRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.updateDestinosResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateDestinos(inValue);
            return retVal.updateDestinosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateDestinosResponse> Isban.Maps.Bussiness.MYAService.Services.updateDestinosAsync(Isban.Maps.Bussiness.MYAService.updateDestinosRequest request) {
            return base.Channel.updateDestinosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateDestinosResponse> updateDestinosAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateDestinosRequest inValue = new Isban.Maps.Bussiness.MYAService.updateDestinosRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateDestinosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.registrarConDestinoResponse Isban.Maps.Bussiness.MYAService.Services.registrarConDestino(Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest request) {
            return base.Channel.registrarConDestino(request);
        }
        
        public string registrarConDestino(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest inValue = new Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.registrarConDestinoResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).registrarConDestino(inValue);
            return retVal.registrarConDestinoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.registrarConDestinoResponse> Isban.Maps.Bussiness.MYAService.Services.registrarConDestinoAsync(Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest request) {
            return base.Channel.registrarConDestinoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.registrarConDestinoResponse> registrarConDestinoAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest inValue = new Isban.Maps.Bussiness.MYAService.registrarConDestinoRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).registrarConDestinoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.getParametrosResponse Isban.Maps.Bussiness.MYAService.Services.getParametros(Isban.Maps.Bussiness.MYAService.getParametrosRequest request) {
            return base.Channel.getParametros(request);
        }
        
        public string getParametros(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.getParametrosRequest inValue = new Isban.Maps.Bussiness.MYAService.getParametrosRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.getParametrosResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).getParametros(inValue);
            return retVal.getParametrosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getParametrosResponse> Isban.Maps.Bussiness.MYAService.Services.getParametrosAsync(Isban.Maps.Bussiness.MYAService.getParametrosRequest request) {
            return base.Channel.getParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getParametrosResponse> getParametrosAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.getParametrosRequest inValue = new Isban.Maps.Bussiness.MYAService.getParametrosRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).getParametrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.registrarResponse Isban.Maps.Bussiness.MYAService.Services.registrar(Isban.Maps.Bussiness.MYAService.registrarRequest request) {
            return base.Channel.registrar(request);
        }
        
        public string registrar(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.registrarRequest inValue = new Isban.Maps.Bussiness.MYAService.registrarRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.registrarResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).registrar(inValue);
            return retVal.registrarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.registrarResponse> Isban.Maps.Bussiness.MYAService.Services.registrarAsync(Isban.Maps.Bussiness.MYAService.registrarRequest request) {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.registrarResponse> registrarAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.registrarRequest inValue = new Isban.Maps.Bussiness.MYAService.registrarRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).registrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.updateEstadoClienteResponse Isban.Maps.Bussiness.MYAService.Services.updateEstadoCliente(Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest request) {
            return base.Channel.updateEstadoCliente(request);
        }
        
        public string updateEstadoCliente(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest inValue = new Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.updateEstadoClienteResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateEstadoCliente(inValue);
            return retVal.updateEstadoClienteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateEstadoClienteResponse> Isban.Maps.Bussiness.MYAService.Services.updateEstadoClienteAsync(Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest request) {
            return base.Channel.updateEstadoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.updateEstadoClienteResponse> updateEstadoClienteAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest inValue = new Isban.Maps.Bussiness.MYAService.updateEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).updateEstadoClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.Maps.Bussiness.MYAService.getSuscripcionesResponse Isban.Maps.Bussiness.MYAService.Services.getSuscripciones(Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest request) {
            return base.Channel.getSuscripciones(request);
        }
        
        public string getSuscripciones(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest inValue = new Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.Maps.Bussiness.MYAService.getSuscripcionesResponse retVal = ((Isban.Maps.Bussiness.MYAService.Services)(this)).getSuscripciones(inValue);
            return retVal.getSuscripcionesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getSuscripcionesResponse> Isban.Maps.Bussiness.MYAService.Services.getSuscripcionesAsync(Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest request) {
            return base.Channel.getSuscripcionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.Maps.Bussiness.MYAService.getSuscripcionesResponse> getSuscripcionesAsync(string xmlFirmado) {
            Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest inValue = new Isban.Maps.Bussiness.MYAService.getSuscripcionesRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.Maps.Bussiness.MYAService.Services)(this)).getSuscripcionesAsync(inValue);
        }
    }
}
